### ISSUE TITLE
Script fails when there are no crash clusters in last 7  days

### ISSUE THREAD

**Issue by julianharty** [commercetest/vitals-scraper#11]
For low-volumes of crashes, sometimes there are no crash clusters for the default period using by Google Android Vitals' UI, however there may be crash clusters for longer periods (e.g. 60 days). Our script currently fails and the browser awaits someone to close it down (and then kill the script).

Changing the URL to add `&lastReportedRange=LAST_60_DAYS` would enable the script to retrieve the older crash clusters (provided they're in the date range being requested in the script/by the user).

Example:
`npm run start:dev -- --accountId=--cut--  --packageName=org.kiwix.kiwixcustomwikimedfa --format=json`
```
✔ Logging In
✖ Getting and writing crash clusters to [/Users/julianharty/myopensourceprojects/vitals-scraper/android-crash-clusters_1565944819364.json]
✖ [09:40:54] Failed to scrape after [62671ms]: TimeoutError: waiting for selector "[data-type="errorLocation"]" failed: timeout 30000ms exceeded
    at new WaitTask (/Users/julianharty/myopensourceprojects/vitals-scraper/node_modules/puppeteer/lib/DOMWorld.js:554:28)
    at DOMWorld._waitForSelectorOrXPath (/Users/julianharty/myopensourceprojects/vitals-scraper/node_modules/puppeteer/lib/DOMWorld.js:483:22)
    at DOMWorld.waitForSelector (/Users/julianharty/myopensourceprojects/vitals-scraper/node_modules/puppeteer/lib/DOMWorld.js:437:17)
    at Frame.waitForSelector (/Users/julianharty/myopensourceprojects/vitals-scraper/node_modules/puppeteer/lib/FrameManager.js:606:47)
    at Frame.<anonymous> (/Users/julianharty/myopensourceprojects/vitals-scraper/node_modules/puppeteer/lib/helper.js:109:23)
    at Page.waitForSelector (/Users/julianharty/myopensourceprojects/vitals-scraper/node_modules/puppeteer/lib/Page.js:1073:29)
    at /Users/julianharty/myopensourceprojects/vitals-scraper/src/Downloader.ts:187:20
    at Generator.next (<anonymous>)
    at /Users/julianharty/myopensourceprojects/vitals-scraper/src/Downloader.ts:7:71
    at new Promise (<anonymous>)
  -- ASYNC --
    at Frame.<anonymous> (/Users/julianharty/myopensourceprojects/vitals-scraper/node_modules/puppeteer/lib/helper.js:108:27)
    at Page.waitForSelector (/Users/julianharty/myopensourceprojects/vitals-scraper/node_modules/puppeteer/lib/Page.js:1073:29)
    at /Users/julianharty/myopensourceprojects/vitals-scraper/src/Downloader.ts:187:20
    at Generator.next (<anonymous>)
    at /Users/julianharty/myopensourceprojects/vitals-scraper/src/Downloader.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/julianharty/myopensourceprojects/vitals-scraper/src/Downloader.ts:3:12)
    at getCrashClusterIds (/Users/julianharty/myopensourceprojects/vitals-scraper/src/Downloader.ts:186:12)
    at Downloader.<anonymous> (/Users/julianharty/myopensourceprojects/vitals-scraper/src/Downloader.ts:52:47)
    at Generator.next (<anonymous>) {
  name: 'TimeoutError'
}
```

**Comment by julianharty** [comment]
Also applies to 
- `org.kiwix.kiwixcustomwikispecies` which has a single crash cluster for 60 days.
- `org.kiwix.kiwixcustomwikimedor` which has 4 crash clusters for 60 days.
- `org.kiwix.kiwixcustomvenezuela` which has 2...
- `org.kiwix.kiwixcustomtunisie` has 1...

**Comment by ISNIT0** [comment]
I'd replace all occurrences of `page.waitFor('[data-type="errorLocation"]')` with something like `page.waitFor('[data-type="errorLocation"],[role=article]>div[aria-hidden=true]')`.
This matches when we have content, **or** when the "no errors found" message shows

**Comment by julianharty** [comment]
Here's some more info for the `0 Crash clusters` text

`<div class="gwt-Label" style="">0 crash clusters</div>`

Which pleasingly easy to locate using the following! (what's wrong with adding useful and usable element labels?)
`body > div:nth-child(5) > div > div:nth-child(2) > div > div:nth-child(2) > div > div.GNVPVGB-T-c > div > div.GNVPVGB-G-m > div > div:nth-child(1) > div > div > div.GNVPVGB-j-z.GNVPVGB-j-U > div > section > div.GNVPVGB-Yi-f > div.GNVPVGB-Yi-l > div`

xpath reduces this mess to a terser but no clearer:
`/html/body/div[2]/div/div[2]/div/div[2]/div/div[3]/div/div[2]/div/div[1]/div/div/div[2]/div/section/div[8]/div[1]/div`

Using CSS selectors finds a set (of 6) results for
`$$('.gwt-Label')`

Of these the even ones don't have any textContent while the odd ones do. Of these, the last one has the textContent of `0 crash clusters`.

**Comment by julianharty** [comment]
It seems that there is an element returned with `textContent: "Real-time crashes"` regardless of whether there are crash clusters, or none. So a possible enhancement might be to wait for `.gwt-Label` and then first check for this text appearing before then trying to process the page and obtain any crash clusters.

**Comment by julianharty** [comment]
I believe we've finally got the script working sufficiently well so it copes with this scenario. Closing this issue accordingly.
