### ISSUE TITLE
Bug: scraper aborts when crashes for all packages requested (using *)

### ISSUE THREAD

**Issue by julianharty** [commercetest/vitals-scraper#41]
Turns out we didn't fully implement the logic to enable the shortcut of `*` to scrape all the packages for an account. Instead the program quits because * does not match any of the actual packages.

```
npm run start:dev -- --accountId=<removed>  --packageName=* --mode=crashes

> vitals-scraper@1.0.7 start:dev /Users/julianharty/myopensourceprojects/vitals-scraper
> ts-node-dev -r tsconfig-paths/register src/index.ts "--accountId=<removed>" "--packageName=*" "--mode=crashes"

Using ts-node version 8.0.3, typescript version 3.3.3333
ℹ [22:09:27] Running scraper in [crashes] mode
ℹ [22:09:27] [--verbose] is not set, defaulting to[false]
ℹ [22:09:27] [--parallel] is not set, defaulting to[1]
ℹ [22:09:27] [--days] is not set, defaulting to[7]
ℹ [22:09:27] [--format] is not set, defaulting to [json](options: json | csv)
ℹ [22:09:27] [--outDir] is not set, using [/<removed>/myopensourceprojects/vitals-scraper]
ℹ [22:09:27] [--numExceptions] is not set, using [all]



✔ Logging In
✖ [22:10:23] Failed to scrape after [56040ms]: Error: Package name[*]is not available
    at Object.<anonymous> (/<removed>/myopensourceprojects/vitals-scraper/src/scrapeCrashes.ts:103:23)
    at Generator.next (<anonymous>)
    at fulfilled (/<removed>/myopensourceprojects/vitals-scraper/src/scrapeCrashes.ts:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

```

**Comment by julianharty** [comment]
Fixed by https://github.com/commercetest/vitals-scraper/commit/6fa5f08893c6ea4d472f01e7ef59bb607443f96f
