### ISSUE TITLE
Scraper fails when scraping exception details

### ISSUE THREAD

**Issue by julianharty** [commercetest/vitals-scraper#5]
The scraper failed early into retrieving the details of the various crash clusters. Two issues were reported in the output, I don't know if they're related and/or if one caused the other (just because one appears earlier than the other in the log doesn't necessarily mean the first causes the second).

I installed the vitals-scraper package (version 1.03) using npm rather than running the code from the source.

Here are the two issues:
```
TimeoutError: waiting for selector "section[role=article] .gwt-HTML strong" failed: timeout 30000ms exceeded
```

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
```
And here's the full output.
```
 vitals-scraper --accountId={removed} --packageName=org.kiwix.kiwixmobile --format=json
ℹ [20:29:38] [--verbose] is not set, defaulting to [false]
ℹ [20:29:38] [--parallel] is not set, defaulting to [1]
ℹ [20:29:38] [--outDir] is not set, using [/Users/julianharty/sandbox/vitals-scraper]



✔ Logging In
⠸ Getting and writing crash clusters to [/Users/julianharty/sandbox/vitals-scraper/android-crash-clusters_1556047936913.json]Got crash cluster detail [0/702] [0%]
⠸ Getting and writing crash clusters to [/Users/julianharty/sandbox/vitals-scraper/android-crash-clusters_1556047936913.json]Got crash cluster detail [1/702] [0%]
⠴ Getting and writing crash clusters to [/Users/julianharty/sandbox/vitals-scraper/android-crash-clusters_1556047936913.json]Got crash cluster detail [2/702] [0%]
⠦ Getting and writing crash clusters to [/Users/julianharty/sandbox/vitals-scraper/android-crash-clusters_1556047936913.json]Got crash cluster detail [3/702] [0%]
⠹ Getting and writing crash clusters to [/Users/julianharty/sandbox/vitals-scraper/android-crash-clusters_1556047936913.json]Got crash cluster detail [4/702] [1%]
✖ Getting and writing crash clusters to [/Users/julianharty/sandbox/vitals-scraper/android-crash-clusters_1556047936913.json]
✖ [20:35:26] Failed to scrape after [348813ms]: { TimeoutError: waiting for selector "section[role=article] .gwt-HTML strong" failed: timeout 30000ms exceeded
    at new WaitTask (/usr/local/lib/node_modules/vitals-scraper/node_modules/puppeteer/lib/DOMWorld.js:554:28)
    at DOMWorld._waitForSelectorOrXPath (/usr/local/lib/node_modules/vitals-scraper/node_modules/puppeteer/lib/DOMWorld.js:483:22)
    at DOMWorld.waitForSelector (/usr/local/lib/node_modules/vitals-scraper/node_modules/puppeteer/lib/DOMWorld.js:437:17)
    at Frame.waitForSelector (/usr/local/lib/node_modules/vitals-scraper/node_modules/puppeteer/lib/FrameManager.js:608:47)
    at Frame.<anonymous> (/usr/local/lib/node_modules/vitals-scraper/node_modules/puppeteer/lib/helper.js:111:23)
    at Page.waitForSelector (/usr/local/lib/node_modules/vitals-scraper/node_modules/puppeteer/lib/Page.js:1073:29)
    at /usr/local/lib/node_modules/vitals-scraper/bin/Downloader.js:205:20
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/vitals-scraper/bin/Downloader.js:7:71
    at new Promise (<anonymous>)
  -- ASYNC --
    at Frame.<anonymous> (/usr/local/lib/node_modules/vitals-scraper/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.waitForSelector (/usr/local/lib/node_modules/vitals-scraper/node_modules/puppeteer/lib/Page.js:1073:29)
    at /usr/local/lib/node_modules/vitals-scraper/bin/Downloader.js:205:20
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/vitals-scraper/bin/Downloader.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/vitals-scraper/bin/Downloader.js:3:12)
    at readExceptionsFromCrashPage (/usr/local/lib/node_modules/vitals-scraper/bin/Downloader.js:204:12)
    at Downloader.<anonymous> (/usr/local/lib/node_modules/vitals-scraper/bin/Downloader.js:89:42)
    at Generator.next (<anonymous>) name: 'TimeoutError' }
Got crash cluster detail [5/702] [1%]
Got crash cluster detail [6/702] [1%]
Got crash cluster detail [7/702] [1%]
Got crash cluster detail [8/702] [1%]
Got crash cluster detail [9/702] [1%]
Got crash cluster detail [10/702] [1%]
Got crash cluster detail [11/702] [2%]
Got crash cluster detail [12/702] [2%]
Got crash cluster detail [13/702] [2%]

<--- Last few GCs --->

[31729:0x105800000]  1372382 ms: Mark-sweep 1307.7 (1451.2) -> 1307.6 (1451.2) MB, 5684.3 / 0.0 ms  allocation failure GC in old space requested
[31729:0x105800000]  1377430 ms: Mark-sweep 1307.6 (1451.2) -> 1307.7 (1432.2) MB, 5047.7 / 0.0 ms  last resort GC in old space requested
[31729:0x105800000]  1382791 ms: Mark-sweep 1307.7 (1432.2) -> 1307.7 (1432.2) MB, 5360.4 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x30e8fff0427d]
Security context: 0x416a71a06a9 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [/usr/local/lib/node_modules/vitals-scraper/bin/Downloader.js:~3] [pc=0x30e900257662](this=0x41686a822e1 <undefined>,resolve=0x416b60828f1 <JSFunction (sfi = 0x41686a9b971)>,reject=0x416b6082929 <JSFunction (sfi = 0x41686a9b9f9)>)
    2: new Promise(aka Promise)(this=0x41686a82321 <the_hole>,0x416b6082841 <JSFunctio...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewStruct(v8::internal::InstanceType, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::Factory::NewPrototypeInfo() [/usr/local/bin/node]
 7: v8::internal::Map::GetOrCreatePrototypeInfo(v8::internal::Handle<v8::internal::Map>, v8::internal::Isolate*) [/usr/local/bin/node]
 8: v8::internal::JSObject::MakePrototypesFast(v8::internal::Handle<v8::internal::Object>, v8::internal::WhereToStart, v8::internal::Isolate*) [/usr/local/bin/node]
 9: v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>) [/usr/local/bin/node]
10: v8::internal::Runtime_LoadIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x30e8fff0427d
12: 0x30e900257662
13: 0x30e9002270c2
14: 0x30e8fff0fc01
Abort trap: 6
Julians-MBP:vitals-scraper julianharty$ 
```

**Comment by ISNIT0** [comment]
Have we been able to reproduce this recently?

**Comment by julianharty** [comment]
Let's close this as we've not seen this error in the last couple of months, at least. Thanks for the reminder to check.
